### ISSUE TITLE
Install Fedora 6

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#1]
## Story
_As a Repository Administrator, I want to use Fedora 6 software, so that I can provide a stable and modern infrastructure for preserving OpenEmory content_

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Links to Additional Information
Add [links](https://www.emory.edu/) here
Refs: prior work tickets for Fedora 6 installation and S3 configuration research:
https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/39
https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/103

#### Checklist
- [ ] Install within AWS account 70
- [ ] Create Arch, test, prod instances
- [ ] Configure storage/ocfl root to use S3 storage (see separate epic/issue)

**Comment by eporter23** [comment]
To do: Split out into 3 generic tickets for arch, test, prod
