### ISSUE TITLE
Administrative Features

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#188]
## Story
_As a Library Deposit Supervisor, I want to allow users to immediately publisher their deposits but later review the material submitted, so that I can augment or correct the data provided_

_As a Collection Manager, I want to monitor usage activity for OpenEmory material, so that I can report statistics to the Emory Libraries annual reporting process_

_As a Preservation Curator, I want to restrict deletion of material to approved parties only, so that we do not delete material without following existing Emory Libraries policies_

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
This epic groups together various Administrator features needed to support the OpenEmory deposit service.

#### Links to Additional Information
This document outlines some [high-level workflow and other needs identified by SCO](https://docs.google.com/document/d/1NE7S1PrZTmi4FwDGIHl5CPaAiMS42g2Tk3GC7mRmwEk/edit#heading=h.hbyuy15xf21e)

#### Checklist
- [x] Review and approval process
- [x] Administrative metadata
- [x] Admin-only display of selected information
- [x] Permissions management and automation of deposit relationships to Admin Sets and Collections
- [x] Ability for Admins to withdraw or set selected items to Private
- [ ] Restriction of Delete options to Admins only
- [ ] Statistics page (resolve error or hide from display)
- [x] Dashboard Resource Types > adjust to our local field equivalent
- [ ] Google Analytics and other reporting functions
- [x] User Collections [these will be user-creatable but private]

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
