### ISSUE TITLE
Configure S3 Storage for Fedora

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#2]
## Story: 
_As a Preservation Curator, I want to establish preservation storage in S3, so that OpenEmory content can be preserved and monitored using the same processes as Emory Digital Collections material_

## Acceptance Criteria:

- Establish new, separate S3 buckets for OpenEmory content within our AWS account 70
- Ensure that we can utilize the same AWS lambda fixity checking process in AWS as we use for "cor" buckets

### Notes:
See prior work ticket for configuring Fedora 6 to use S3:
https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/103

Naming convention for new S3 buckets:

- fedora-depo-binaries
- fedora-depo-binaries-test
- fedora-depo-binaries-arch

### Checklist:
- [ ] Create S3 buckets for arch, test and production environments
- [ ] Establish second copy/replication process for each environment (for easier templating)
- [ ] Aim for daily replication (we can adjust if run into performance issues)
- [ ] Enable cross-region replication

**Comment by eporter23** [comment]
We may need a separate ticket for fixity checking specifically

**Comment by eporter23** [comment]
We may need a separate repo for Cloud formation scripts etc.
