### ISSUE TITLE
Install/configure SOLR

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#3]
## Story

Story: As a Repository Administrator, I want to leverage our existing SOLR infrastructure for OpenEmory content, so that we can move toward shared discovery  across multiple applications

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Checklist

- [x] Create a new SOLR collection for openemory within the existing solr-cor instances
- [x] Establish new collection within arch, test and production 
- [x] SOLR config for Hyrax (can start with basic Hyrax configs)
- [x] Spike for Zookeeper usage/replacement? (optional, time may not permit this and it will impact other apps)
