### ISSUE TITLE
ART and Security Reviews

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#32]
## Story
_As a Repository Administrator, I want to pass required campus IT reviews, so that we are in compliance with security and architecture requirements_

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here

#### Links to Additional Information
[ART sharepoint site](https://emory.sharepoint.com/sites/ArchitectureReviewTeamART): this seems to be the most current info and contains documents to submit 
ART@emory.edu contact email re: questions 

#### Checklist
- [x] Determine current process for ART/Security reviews
- [x] Determine if Security review is initiated separately (yes, it is)
- [x] Submit initial Security review intake form
- [x] Prepare required documentation
- [x] Submit required documentation
- [x] Followup on any questions by review teams
