### ISSUE TITLE
Create template for PID migration tracking

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#397]
For migration we will need:

- [x] Overall [tracking worksheet for batches](https://docs.google.com/spreadsheets/d/1L4fNt6XOmkLj0o0hyCxwTuNmtquh_woJK-ojVWpetWw/edit?gid=0#gid=0)

- [x] SOLR query to generate sets of IDs for the following, where records are Active (`state:"A"`) and not withdrawn (`withdrawn:false`) and contains a content data stream (`dsids:content`). We want to match on a datastream with the exact name of `content`, but not `contentMetadata`. Additional parameters may be needed for the following factors: review queue, embargo, and specific publication types that need manual remediation (see separate tickets for special cases)

- [x] To determine: sorting strategy to ensure we do not duplicate or overlap when exporting batches. Sort by review_date may be one option, so we could load the oldest records first. This would also help ensure that "Recently Uploaded" content on the homepage is accurate for migrated records.
- [x] The exported results should include `pid,record_type,dsids,pubyear,state,withdrawn,review_date,embargo_end`.

**Comment by eporter23** [comment]
After working with this, I think that exporting in sets of several thousand at a time, sorted by review_date may be the best way to help avoid any overlaps. I am also adding more data to the SOLR query to help filter by certain other factors such as embargo, review queue, etc.

**Comment by eporter23** [comment]
After reviewing the output of this on 1000 pids, the above query returned some unwanted records with no content datastream. I'm now testing out some revisions as noted below:

<img width="1380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2s2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b75c2b9ecb2107879122ba6daaae1b3d898c1d5d/OEPIDs-SOLR-v3.png" alt="OEPIDs-SOLR-v3.png" />
