### ISSUE TITLE
Install and configure base Hyrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#4]
## Story
 As a Repository Administrator, I want to implement Hyrax with Valkyrie, so that Emory can leverage the most current code and performance optimizations

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
Add notes here
Reqs

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Checklist
- [ ] Implement Hyrax 5x with Valkyrie
- [ ] Implement instances for arch, test and production
- [ ] Configure for use with Fedora 6
- [ ] Configure for use with SOLR
- [ ] Ensure SCO users can access Hyrax instance
- [ ] Working domain names?
- [ ] Address any immediate Hyrax/Fedora 6 bugs
- [ ] Use built-in RIIIF to start?
- [ ] Configure Hyrax "Feature flipper" settings
- [ ] Establish Admin users/group for initial setup and testing
- [ ] Perform additional Hyrax 5.x upgrade(s) before project close if needed
