### ISSUE TITLE
Setup Users, Groups and Roles for Hyrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#44]
## Story
_As a Repository Administrator, I want to establish system permissions for OpenEmory users, so that activities related to deposit, preservation, and discovery are carefully managed_ 

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
**This epic is still pending additional detail.** 

#### Links to Additional Information
[Worksheet for OpenEmory users (in progress)](https://docs.google.com/spreadsheets/d/1VO7EwDHfXAEweyVRVsGl-F5yv8YtCqXwUr7B9Yqb2fg/edit#gid=223781095)
[Prior epic for Curate Collection Groups setup](https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/gh/emory-libraries/dlp-curate/275)
[PR for some initial user setup in Curate](https://github.com/emory-libraries/dlp-curate/pull/583/files)

#### Checklist
- [x] Establish initial users to access the application while infrastructure and early development setup begins
- [x] Establish long-term users (tied to Shibboleth)
- [x] Establish required Hyrax roles (admin, registered user)
- [x] Establish required, custom Hyrax groups for OpenEmory material
