### ISSUE TITLE
Install databases for Hyrax use

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#5]
## Story
As a Repository Administrator, I want to implement required database components in AWS, so that we can utilize necessary functionality within Hyrax software

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
During our technical design session in Dec 2023, we discussed having a preference for using Postgres for our Hyrax applications in that it may be easier to configure with Hyrax, and may also be easier for our Middleware team to support.

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Checklist
- [ ] Install Postgres or MySQL using RDS in AWS in Account 70
- [ ] Install arch, test, and production instances
- [ ] Configure new Hyrax applications to use these databases

**Comment by eporter23** [comment]
3 separate tickets: arch, test, prod
