### ISSUE TITLE
Preservation Metadata [placeholder]

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#58]
---
name: Epic
about: Epic/user story template using LTDS best practices

---

## Story
As a [user profile], I want [functionality], so that [business goal]

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
For this epic, we will bring over Preservation Events and Workflows metadata as implemented for Curate.

#### Links to Additional Information
Add [links](https://www.emory.edu/) here

#### Checklist
- [ ] Preservation Workflows metadata for Works
- [ ] Preservation Events metadata for Works
- [ ] Preservation Events metadata for FileSets
- [ ] Enhanced Technical metadata for FileSets

#### Given/When/Then
* Given (some context) and (some other optional context)
* When (some action is carried out)
* Then (a set of observable consequences should occur)
