### ISSUE TITLE
Sitewide branding (header, footer, other global elements)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#8]
## Story
_As an OpenEmory user, I want to understand that I am interacting with an Emory Libraries resource, so that I can have a more consistent user experience with other Libraries applications and trust the source of the information I am utilizing_

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
For this epic, we should work to incorporate UI/branding conventions from current Emory Libraries websites and applications. Mockups can be created as part of the work for this epic. We will do additional styling refinements in later work during the project.

#### Links to Additional Information
Design References:

- [Pattern Library](http://template.library.emory.edu/styleguide/patternlibrary/current/) / Figma
- [Emory Digital Collections](https://digital.library.emory.edu) (Blacklight)
- [Library Search](https://search.libraries.emory.edu) (Blacklight)
- [Nurax](https://pg.nurax.samvera.org) (vanilla Hyrax application maintained by the Samvera Community) - useful for reviewing an "out of the box" Hyrax before we get ours set up
- [UI audit from 2019 for an earlier version of Hyrax](https://docs.google.com/presentation/d/1sqJfKe4phu7-ZBdrcij1a_b0IGPqPAAX5vQqq_OeQRA/edit#slide=id.g5a45e2d167_0_0) - may be useful for skimming all the different types of page views generated by a Hyrax application 
- [Early mockup for header and footer for OpenEmory](https://docs.google.com/drawings/d/11WdK_G1qkvITa0UlA0xRlNUJZ2MjjZiGIF4o2wLE8t0/edit) (to be refined)

Examples of wireframes/mockups produced for other projects:

- Library Search: [detailed homepage design](https://www.figma.com/file/drcXB81ScJre4Y3SPFSv3C/Emory-Blacklight-Homepage-Mockup?type=design&node-id=237-4284&mode=design) (Figma)
- Library Search: [availability status with modal](https://docs.google.com/drawings/d/1gnw0hA1dT_lz9zMr6QxUfFRspc7IYVMz3JiXqQJWDy4/edit) (Google Drawing)
- Library Search: [results page showing physical holding summary on click](https://docs.google.com/drawings/d/1cCdbtg5YaN3YwfTdPmzQjzTeKKu2dMHBHs0_583MkUo/edit) (Google Drawing)
- Library Search: [buttons and badge behavior](https://codepen.io/eporter23/pen/GREJqxw) (codepen)
- Emory Digital Collections: [homepage](http://emilyporter.net/emory/blacklight-headerA-4.html) (HTML/CSS mockup)
- Emory Digital Collections: [static page content layout template](https://docs.google.com/document/d/1xRp_yZi-44z4K8pUMbZahXVQBlBo43wT47lAGU5eoeE/edit) (Google doc)
- [Wireframe template with EUL colors](https://docs.google.com/drawings/d/1c1EP6foBBHmDAXYuNoBcYX6LMoN4tDT9_AZDLLav0xU/edit?usp=sharing) (Google Drawing)

#### Checklist
- [x] Develop mockups for major global elements
- [x] Implement styling for header (with search element)
- [x] Implement styling for footer
- [ ] Implement other global styles for typography, links, colors, etc.
