### ISSUE TITLE
Export and Transform Legacy Data for Migration

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#9]
## Stories
_As a Preservation Curator, I want to export and transform metadata and files from Fedora 3, so that the files and metadata can be packaged and preserved in a structure consistent with Curate material_

_As a Preservation Curator, I want to migrate the OpenEmory collection from Fedora 3 to a modern version, so that we can ensure the stability of preservation for this content_

## Acceptance Criteria
_Use one or more of the following options to provide acceptance criteria._

#### Notes
For this epic, we will identify a process for exporting and transforming data from Fedora 3 so that it can be reformatted as bulk-ingest packages for Hyrax. We won't complete a full migration or Bulkrax configuration in this epic, but instead focus on building tools to support those needs.

During our migration pilot in 2023, we learned that using the Fedora 3 to 6 migration utility will not support our needs. Instead, we must find another way to export selected data from Fedora/SOLR so that we can then re-ingest it through Bulkrax into Hyrax. 

Fedora 3 stores all metadata and content as files. Some files will be retained as-is, some will be used to extract metadata but do not need to be preserved, and some do not need to be migrated at all. A preliminary check of SOLR reveals not all data used in record display are stored/indexed, so we need to consider if it will be more effective to extract metadata directly from the descMetadata (MODS) and provenanceMetadata (PREMIS) XML files. 

Another issue we need to work around is that files downloaded directly from Fedora 3 do not append a file extension. The mime type is stored in Fedora, but is not appended to Fedora downloads. Downloads from the OpenEmory application do seem to assign the correct extension when providing a download. Ideally we would ensure all files have an assigned extension prior to re-ingesting through Hyrax.

#### Links to Additional Information
[Lessons learned from 3 to 6 migration testing](https://docs.google.com/document/d/1qnauwDdlkflJ_I7T8y8CJ6gNEU7jjQT0dZ6olTLoPdI/edit#heading=h.7iryekwnm77r)
[Prior work to assess Fedora 3 export option](https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/222)
[Prior work to assess data remediation needs](https://docs.google.com/document/d/1h-8vJvu1qXRv4OLYgsCzSJwQpBrOdzCYYhfigjtg-g8/edit#heading=h.aod52fg859ve)
[Representative objects manually built in Curate-test
](https://curate-test.library.emory.edu/dashboard/collections/730bvq83p4-cor?locale=en)
#### Checklist

**NOTE: Additional details will be added once we determine our path to get data out of the legacy environment.**

- [x] Investigate options to export files from Fedora 3
- [x] Investigate options to extract metadata from selected files (or export metadata from SOLR?)
- [x] Remediate filenames and file extensions as needed if exporting directly from Fedora 3
- [x] Export a small batch of objects from Fedora 3 ([see samples used in 2023 work](https://docs.google.com/spreadsheets/d/1qLzdhhOIXj9ebPAS58qWpWLUD8SMXGeIjR9re0qTfMQ/edit#gid=0))
- [x] Determine staging area where exported files/metadata can be reviewed before ingest into Hyrax
- [x] Identify strategy for packaging files and metadata together for Bulkrax use
